import type { IdentityContext, UUIDv7 } from '#domain/auth/index.js';
import type { Subscription } from '#domain/notifications/index.js';

import type { McpErrorCode } from './error-codes.js';

/**
 * Per-session state held by the in-memory session-store. Keyed by the SDK's
 * `sessionId`. Lifetime: from `initialize` to socket close (graceful or abrupt).
 */
export interface SessionState {
  /** SDK-assigned session id; opaque to us. */
  sessionId: string;
  /** Resolved at `initialize` from the verified Bearer; never mutated. */
  identity: IdentityContext;
  /** UUID v7 generated by the transport for the SubscriberHandle contract. */
  connectionId: UUIDv7;
  /** Presence Registry handle; null between initialize and subscribe wiring. */
  subscription: Subscription | null;
  /**
   * Optional strong reference to the notifier used by the SubscriberHandle's
   * `WeakRef`. Without this anchor the notifier object literal escapes scope
   * and is eligible for GC, which would make `serverRef.deref()` return
   * undefined and silently drop Waggle notifications under memory pressure.
   * Held here for as long as the session lives.
   */
  notifierRef: unknown;
  establishedAt: Date;
  /** Bumped on every tool call. */
  lastSeenAt: Date;
  /** Defense-in-depth flag: if true, requireIdentityFor throws SESSION_INVALIDATED. */
  invalidated: boolean;
}

/**
 * Wrapper passed to tool handlers. Combines the identity (from auth-binding)
 * with per-request data (requestId for correlation, sessionState for callbacks).
 *
 * `IdentityContext` from Auth + Identity does NOT carry `requestId` — this is
 * the transport-only wrapper documented in the tech spec § auth-binding.ts.
 */
export interface RequestContext {
  identity: IdentityContext;
  requestId: UUIDv7;
  sessionState: SessionState;
}

/**
 * Wire-shape of an error that leaves the MCP boundary. The semantic `code`
 * (e.g. RECIPIENT_UNREACHABLE) and `subCode` NEVER cross this boundary — the
 * mapper preserves them only in the structured log for forensics.
 */
export interface WireError {
  code: McpErrorCode;
  message: string;
}

/**
 * Internal helper carried by `mapDomainError` so the caller can both throw the
 * wire error AND log the rich context. Tests assert against this shape.
 */
export interface MappedError {
  wire: WireError;
  /** Original domain code for log only. e.g. `RECIPIENT_UNREACHABLE`. */
  domainCode: string | null;
  /** Original sub-code for log only. e.g. `cell_closed_or_missing`. */
  subCode: string | null;
}
