// SubscriberHandle — interface that the MCP transport implements to represent
// an active client session. Inversion of dependency: the notifications domain
// does not know the MCP SDK; the MCP transport wraps its session behind this
// interface and passes it to `presenceRegistry.subscribe`.
//
// Per the tech spec (Waggle Pipeline + Presence Registry §
// "presence/subscriber-handle.ts"):
//   - `connectionId` is generated by the MCP transport at session accept time
//     (typically uuidv7()). The registry uses it as the key in its internal
//     per-participant Map. Two handles sharing the same `connectionId` make the
//     second subscribe overwrite the first (accepted: buggy client self-sabotage).
//   - `deliver(notification)` is best-effort. The pipeline never re-raises a
//     failed deliver — it logs and continues with the remaining handles. If the
//     handle goes zombie (socket dead), it MUST internally invoke the closure
//     wired via `onClose()` so the registry deregisters it.
//   - `onClose(callback)` is wired by the registry in `subscribe()`: the
//     registry passes a closure that performs `unsubscribe(subscriptionId,
//     participantId)`. The handle invokes it once on detected socket close.

import type { IdentityContext, UUIDv7 } from '#domain/auth/types.js';

import type { WaggleNotification } from '../waggle/types.js';

export interface SubscriberHandle {
  readonly connectionId: UUIDv7;
  readonly callerContext: IdentityContext;
  deliver(notification: WaggleNotification): Promise<void>;
  onClose(callback: () => void): void;
}
